export const PRODUCT_ADD_CLICK = 'PRODUCT_ADD_CLICK';
export const PRODUCT_RECEIVED = 'PRODUCT_RECEIVED';
export const GET_CURRENCY_DATA = 'GET_CURRENCY_DATA';
export const FETCH_CURRENCY_RATES_SUCCESS = 'FETCH_CURRENCY_RATES_SUCCESS';
export const FETCH_CURRENCY_RATES_FAILURE = 'FETCH_CURRENCY_RATES_FAILURE';